openapi: 3.0.1
info:
  title: {{ cookiecutter['_@cortex_inputs']['service_details']['name'] }}
  description: {{ cookiecutter['_@cortex_inputs']['service_details']['description'] }}
  x-cortex-tag: {{ cookiecutter['_@cortex_inputs']['service_details']['tag'] }}
  x-cortex-type: service
  x-cortex-git:
    github:
      repository: {{ cookiecutter['_@cortex_inputs']['git']['repository']['org'] }}/{{ cookiecutter['_@cortex_inputs']['git']['repository']['repoName'] }}
  x-cortex-static-analysis:
    sonarqube:
      alias: SonarCloud
      project: {{ cookiecutter['_@cortex_inputs']['git']['repository']['org'] }}_{{ cookiecutter['_@cortex_inputs']['git']['repository']['repoName'] }}
